" Reset GUI options
set guioptions=
set guioptions+=a  " Use the system GUI clipboard
set guioptions+=c  " Use console dialogs, not popup windows
set guioptions+=M  " Don't load menu.vim (also set in .vimrc)

" Don't use the mouse
set mouse=
